name: Compilation & tests

on: [push, pull_request]

jobs:
  job_build_debug:
    name: Build debug
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Paraswap plugin
        run: |
          make DEBUG=1

      - name: Upload Paraswap binary
        uses: actions/upload-artifact@v2
        with:
          name: paraswap-app-debug
          path: bin
